@extends('layouts.app')
@section('title','Master Schedule')
@section('content')
<div class="mx-auto max-w-7xl"><h1 class="text-3xl font-bold">Master Schedule</h1><p class="mt-1 text-sm text-slate-500">View every reservation and lock or reopen custom dates and time slots.</p>
@if(session('success'))<div class="mt-4 rounded-lg bg-green-50 p-3 text-green-700">{{session('success')}}</div>@endif
<form method="GET" class="mt-5 flex gap-3"><input type="month" name="month" value="{{$month}}" class="rounded-lg border-slate-300"><button class="rounded-lg bg-slate-900 px-4 text-white">View Month</button></form>
<div class="mt-6 grid gap-6 lg:grid-cols-3"><section class="lg:col-span-2 rounded-2xl border bg-white shadow-sm"><h2 class="border-b p-5 font-bold">Reservations</h2><div class="divide-y">@forelse($reservations as $r)<a href="{{route('admin.reservations.show',$r)}}" class="grid gap-2 p-4 hover:bg-slate-50 sm:grid-cols-[8rem_1fr_1fr_auto]"><span class="font-semibold">{{$r->reservation_date->format('M d')}}</span><span>{{$r->event_name}}</span><span class="text-slate-500">{{$r->facility?->facility_name}}</span><span class="text-sm">{{ucwords(str_replace('_',' ',$r->status))}}</span></a>@empty<p class="p-8 text-center text-slate-500">No reservations this month.</p>@endforelse</div></section>
<section class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-bold">Block Date or Slot</h2><form method="POST" action="{{route('admin.schedule.blocks.store')}}" class="mt-4 space-y-3">@csrf<input name="title" required placeholder="Maintenance / Special event" class="w-full rounded-lg border-slate-300"><select name="facility_id" class="w-full rounded-lg border-slate-300"><option value="">All facilities</option>@foreach($facilities as $f)<option value="{{$f->id}}">{{$f->facility_name}}</option>@endforeach</select><div class="grid grid-cols-2 gap-2"><input type="date" name="starts_on" required class="rounded-lg border-slate-300"><input type="date" name="ends_on" required class="rounded-lg border-slate-300"><input type="time" name="start_time" class="rounded-lg border-slate-300"><input type="time" name="end_time" class="rounded-lg border-slate-300"></div><textarea name="reason" placeholder="Reason" class="w-full rounded-lg border-slate-300"></textarea><button class="w-full rounded-lg bg-red-600 p-3 font-semibold text-white">Lock Schedule</button></form></section></div>
<section class="mt-6 rounded-2xl border bg-white shadow-sm"><h2 class="border-b p-5 font-bold">Blackouts and Locks</h2><div class="divide-y">@forelse($blocks as $b)<div class="flex items-center justify-between p-4"><div><strong>{{$b->title}}</strong><p class="text-sm text-slate-500">{{$b->starts_on->format('M d, Y')}} – {{$b->ends_on->format('M d, Y')}} · {{$b->facility?->facility_name ?? 'All facilities'}} @if($b->start_time)· {{$b->start_time}}–{{$b->end_time}}@endif</p></div><form method="POST" action="{{route('admin.schedule.blocks.destroy',$b)}}">@csrf @method('DELETE')<button class="text-sm font-semibold text-blue-700">Release / Open</button></form></div>@empty<p class="p-8 text-center text-slate-500">No blackout periods in this month.</p>@endforelse</div></section></div>
@endsection
