@extends('layouts.app')
@section('title','System Settings')
@section('content')
@php($defaults=['booking_confirmation'=>['subject'=>'MCST Gym Reservation Confirmation','body'=>'Reference: {reference}\nTrack: {tracking_link}'],'priority_reassignment'=>['subject'=>'Reservation Schedule Adjusted','body'=>'Your reservation {reference} was adjusted due to priority handling. Track: {tracking_link}'],'cancellation'=>['subject'=>'Reservation Cancelled','body'=>'Reservation {reference} was cancelled. Reason: {reason}']])
<div class="mx-auto max-w-5xl"><h1 class="text-3xl font-bold">System Configuration</h1><p class="mt-1 text-sm text-slate-500">Configure reservation rules and reusable notification templates.</p>@if(session('success'))<div class="mt-4 rounded-lg bg-green-50 p-3 text-green-700">{{session('success')}}</div>@endif
<form method="POST" action="{{route('admin.settings.update')}}" class="mt-6 space-y-6">@csrf @method('PUT')
<section class="rounded-2xl border bg-white p-6 shadow-sm"><h2 class="font-bold">Reservation Rules</h2><div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="text-sm font-semibold">Maximum booking duration (hours)<input type="number" name="maximum_booking_hours" value="{{old('maximum_booking_hours',$settings['maximum_booking_hours']??8)}}" class="mt-2 w-full rounded-lg border-slate-300"></label><label class="text-sm font-semibold">Minimum notice (days)<input type="number" name="minimum_notice_days" value="{{old('minimum_notice_days',$settings['minimum_notice_days']??3)}}" class="mt-2 w-full rounded-lg border-slate-300"></label><label class="text-sm font-semibold">Maximum advance window (days)<input type="number" name="maximum_advance_days" value="{{old('maximum_advance_days',$settings['maximum_advance_days']??365)}}" class="mt-2 w-full rounded-lg border-slate-300"></label><label class="text-sm font-semibold">Pending auto-cancellation (hours)<input type="number" name="pending_auto_cancel_hours" value="{{old('pending_auto_cancel_hours',$settings['pending_auto_cancel_hours']??72)}}" class="mt-2 w-full rounded-lg border-slate-300"></label></div></section>
@foreach($defaults as $key=>$default)@php($template=$templates[$key]??null)<section class="rounded-2xl border bg-white p-6 shadow-sm"><h2 class="font-bold">{{ucwords(str_replace('_',' ',$key))}}</h2><input name="templates[{{$key}}][subject]" value="{{old("templates.$key.subject",$template?->subject??$default['subject'])}}" class="mt-4 w-full rounded-lg border-slate-300"><textarea name="templates[{{$key}}][body]" rows="5" class="mt-3 w-full rounded-lg border-slate-300">{{old("templates.$key.body",$template?->body??$default['body'])}}</textarea><p class="text-xs text-slate-500">Variables: {reference}, {tracking_link}, {reason}</p></section>@endforeach
<div class="text-right"><button class="rounded-lg bg-blue-600 px-6 py-3 font-semibold text-white">Save Configuration</button></div></form></div>@endsection
