<?php

declare(strict_types=1);

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\DashboardRequest;
use App\Models\AuditLog;
use App\Services\DashboardAnalyticsService;
use Illuminate\View\View;
use Symfony\Component\HttpFoundation\StreamedResponse;

class DashboardController extends Controller
{
    public function __invoke(DashboardRequest $request, DashboardAnalyticsService $analytics): View|StreamedResponse
    {
        $filters = $request->filters();
        $data = $analytics->summarize($filters);
        if ($request->input('export') === 'csv') {
            AuditLog::recordEvent('analytics.export', newValues: ['filters' => $filters, 'format' => 'csv', 'matching_records' => $data['totalReservations']]);

            return $this->csv($analytics, $data, $request->user()->full_name);
        }

        return view('dashboard.admin', $data + [
            'selectedPeriod' => $request->input('period'),
            'overviewReservations' => $analytics->records($filters)->reorder()->orderByDesc('reservation_date')->orderByDesc('start_time')->orderByDesc('id')->limit(5)->get(),
        ]);
    }

    private function csv(DashboardAnalyticsService $analytics, array $data, string $administrator): StreamedResponse
    {
        return response()->streamDownload(function () use ($analytics, $data, $administrator): void {
            $file = fopen('php://output', 'w');
            $write = function (array $values) use ($file): void {
                fputcsv($file, array_map(fn ($value) => preg_match('/^[\s]*[=+@-]/u', (string) $value) ? "'".$value : $value, $values), ',', '"', '');
            };
            $write(['MCST Gymnasium Business Intelligence Report']);
            $write(['Scheduled date range', $data['filters']['date_from'], $data['filters']['date_to']]);
            $write(['Generated at', $data['generatedAt']->format('Y-m-d H:i:s T')]);
            $write(['Generated by administrator', $administrator]);
            foreach ($data['filterLabels'] as $name => $value) {
                $write([$name, $value]);
            }
            $write([]);
            $write(['Summary metric', 'Value']);
            foreach ([
                'Total requests' => $data['totalReservations'], 'Pending review (new + validated)' => $data['pendingReservations'],
                'Overdue requests (at least 7 days)' => $data['oldPending'], 'Approved reservations' => $data['approvedReservations'],
                'Completed events' => $data['completedEvents'], 'Cancellation rate (%)' => $data['cancellationRate'],
                'Scheduled utilization rate (%)' => $data['utilizationRate'], 'Scheduled occupied hours (overlaps merged)' => $data['utilizedHours'],
                'Available operating hours' => $data['availableHours'], 'Average processing time (hours)' => $data['processingHours'],
                'Records with decision timestamps' => $data['processingCount'], 'Previous period requests' => $data['previousTotal'],
                'Previous period change (%)' => $data['change'], 'Expected attendees (approved + completed)' => $data['expectedAttendees'],
                'Feedback responses' => $data['feedbackCount'], 'Average recorded satisfaction rating' => $data['feedbackAverage'],
                'Currently waiting' => $data['waitingCount'], 'Ever waitlisted (history)' => $data['waitingEver'],
                'Promoted to approved (history)' => $data['waitingPromoted'], 'Waiting-list conversion (%)' => $data['waitingConversion'],
                'Completed events with completion timestamp' => $data['completionRecorded'],
                'Peak weekday' => $data['peakWeekday']['label'], 'Peak weekday requests' => $data['peakWeekday']['count'],
                'Peak time slot' => $data['peakTimeSlot']['label'], 'Peak time slot requests' => $data['peakTimeSlot']['count'],
                'Busiest month' => $data['busiestMonth']['label'], 'Busiest month requests' => $data['busiestMonth']['count'],
            ] as $name => $value) {
                $write([$name, $value ?? 'N/A']);
            }
            $write(['Previous reporting period', $data['previousFrom']->toDateString(), $data['previousTo']->toDateString()]);
            $write(['Utilization scope', 'Approved + completed scheduled times, clipped to configured operating hours. Overlaps merged per facility/day. Calendar-day capacity; closures not deducted. Not actual attendance or usage.']);
            $write(['Operating hours', $data['operatingHours'] ? $data['operatingHours']['open'].' - '.$data['operatingHours']['close'] : 'Not configured']);
            $write(['Processing definition', 'Submission to first approval, rejection or cancellation from timestamps/history; records without a valid decision timestamp excluded.']);
            $write([]);
            $write(['Reservation outcomes', 'Count', 'Percentage']);
            foreach ($data['statusBreakdown'] as $row) {
                $write([DashboardAnalyticsService::label($row['status']), $row['count'], $row['percentage'] ?? 'N/A']);
            }
            $write(['Trend period start', 'Trend period end', 'Reservations', 'Partial period']);
            foreach ($data['trendActivity'] as $row) {
                $write([$row['from'], $row['to'], $row['count'], $row['partial'] ? 'Yes' : 'No']);
            }
            $write(['Event type', 'Count', 'Percentage']);
            foreach ($data['eventDemand'] as $row) {
                $write([$row['label'], $row['count'], $row['percentage'] ?? 'N/A']);
            }
            foreach (['requestorDemand' => 'Requestor type', 'weekdayDemand' => 'Weekday', 'timeSlots' => 'Hourly slot (booking overlaps, not utilization)'] as $key => $label) {
                $write([$label, 'Reservations']);
                foreach ($data[$key] as $row) {
                    $write([$row['label'], $row['count']]);
                }
            }
            $write(['Equipment', 'Bookings', 'Requested units', 'Allocated units']);
            foreach ($data['equipmentDemand'] as $row) {
                $write([$row->equipment_name, $row->bookings, $row->requested, $row->allocated]);
            }
            $write(['Cancellation reason group', 'Count']);
            foreach ($data['cancellationReasons'] as $row) {
                $write([$row->reason_group, $row->total]);
            }
            $write([]);
            $write(['Matching records (scheduled date, start time, ID ascending)']);
            $write(['Reference', 'Event', 'Event type', 'Requestor type', 'Facility', 'Scheduled date', 'Start time', 'End time', 'Expected attendees', 'Status']);
            foreach ($analytics->records($data['filters'])->lazy(500) as $row) {
                $write([$row->reference_number, DashboardAnalyticsService::label($row->event_name), DashboardAnalyticsService::label($row->event_type), DashboardAnalyticsService::label($row->reservation_type), $row->facility?->facility_name, $row->reservation_date->toDateString(), $row->start_time, $row->end_time, $row->expected_attendees, DashboardAnalyticsService::label($row->status)]);
            }
            fclose($file);
        }, 'dashboard-reservations.csv', ['Content-Type' => 'text/csv; charset=UTF-8', 'Cache-Control' => 'private, no-store']);
    }
}
